"""
agent_06_build_deck.py  —  Build Clean OPM-Native Deck
=======================================================
Takes the anonymised DATA file and produces a cleaner, better-documented
version that runs natively in OPM Flow without patching.

Why a clean deck matters:
  The input DATA file was exported from Eclipse and contains keywords
  and formatting conventions that are Eclipse-specific.  Some of these
  cause OPM to issue warnings, require --parsing-strictness=low to
  accept, or are simply dead weight that confuses readers new to OPM.
  This agent strips those out and adds OPM-oriented section headers and
  comments, producing a deck that:
    - Runs in OPM without any command-line workarounds
    - Documents any non-standard settings clearly
    - Serves as the shareable, publishable version of the model

Transformations applied:
  1. Remove LICENSES block (Eclipse-only licence flag; OPM ignores but warns)
  2. Remove WCUTBACK keywords (Eclipse extension; not supported in OPM)
  3. Remove GLIFTOPT with WLIFTOPT if gas-lift is not being optimised
     (model uses fixed WCONPROD gas lift rates)
  4. Add OPM-style section banner comments
  5. Add a header block identifying this as an OPM-native deck
  6. Preserve all physics, grid, and schedule data exactly

Output:
  {output_dir}/FIELD_X_001_OPM_CLEAN.DATA

The prediction agent (agent_07) uses this clean deck as its base.

Exits 1 if the source DATA file is not found.
"""

import os, re, sys
from pathlib import Path

OFX_DATA_FILE  = os.environ.get("OFX_DATA_FILE",  "data/FIELD_X_001.DATA")
OFX_OUTPUT_DIR = os.environ.get("OFX_OUTPUT_DIR", "output")

# Keywords to suppress (remove the keyword line and its content up to /)
# These are Eclipse-only and cause OPM warnings or are no-ops.
REMOVE_KEYWORDS = {
    "LICENSES",     # Eclipse licence block
    "MEMORY",       # Eclipse memory hint — ignored by OPM
    "WCUTBACK",     # Eclipse extension — not in OPM
}


def strip_keyword_block(text: str, keyword: str) -> str:
    """Remove a keyword block: keyword name through the standalone '/' terminator.

    Eclipse keyword blocks end with a line containing only '/' (the record
    terminator).  Intermediate lines may also contain '/' as part of data
    records (e.g. 'gaslift' /) so we must match to the *standalone* slash —
    a line where '/' is the only non-whitespace character.
    """
    pattern = rf'^{keyword}\b[^\n]*\n(?:(?!/\s*$)[^\n]*\n)*^/\s*\n'
    replaced = re.sub(
        pattern,
        f"-- [{keyword} removed -- not required for OPM]\n",
        text,
        flags=re.MULTILINE,
    )
    return replaced


def add_section_banners(text: str) -> str:
    """Insert OPM-style section header banners before each major keyword."""
    sections = {
        "RUNSPEC": "RUNSPEC  — Run specification",
        "GRID":    "GRID     — Grid geometry and properties",
        "PROPS":   "PROPS    — PVT and relative permeability",
        "REGIONS": "REGIONS  — Region arrays",
        "SOLUTION":"SOLUTION — Initial conditions",
        "SUMMARY": "SUMMARY  — Output vector requests",
        "SCHEDULE":"SCHEDULE — Well and group controls / time stepping",
    }
    for kw, label in sections.items():
        banner = (
            f"\n-- {'='*60}\n"
            f"-- {label}\n"
            f"-- {'='*60}\n"
        )
        # Only add banner if keyword is on its own line and not already preceded by a banner
        text = re.sub(
            rf'\n(?<!-- ={"{60}"})\n({kw}\s*\n)',
            rf'\n{banner}\1',
            text
        )
    return text


OPM_HEADER = """\
-- ===========================================================
-- OPM Flow — Clean Deck
-- Generated by agent_06_build_deck.py
-- Source model: Offshore Field X  (anonymised)
-- Simulator: OPM Flow (open-source, https://opm-project.org)
--
-- This deck has been cleaned of Eclipse-specific keywords
-- that are not required for OPM Flow.  It runs without
-- --parsing-strictness=low.
-- ===========================================================

"""


def main():
    print("\nAgent 06 — Build Clean OPM Deck")
    print("-" * 60)

    src = Path(OFX_DATA_FILE)
    if not src.exists():
        print(f"  ERROR: DATA file not found: {src}")
        sys.exit(1)

    dst = Path(OFX_OUTPUT_DIR) / "FIELD_X_001_OPM_CLEAN.DATA"

    print(f"  Reading: {src}")
    with open(src, "r", errors="replace") as fh:
        text = fh.read()

    print(f"  Original: {len(text):,} characters")

    # 1. Remove Eclipse-only keyword blocks
    for kw in REMOVE_KEYWORDS:
        before = text.count(kw + "\n") + text.count(kw + " ")
        if before > 0:
            text = strip_keyword_block(text, kw)
            print(f"  Removed keyword: {kw}")

    # 2. Remove GLIFTOPT block (uses fixed WCONPROD gas lift; no optimiser)
    if "GLIFTOPT" in text:
        text = strip_keyword_block(text, "GLIFTOPT")
        print("  Removed keyword: GLIFTOPT (fixed WCONPROD gas lift rates used instead)")

    # 3. Add OPM header at top (after any leading comments)
    # Find first non-comment line
    lines = text.split("\n")
    insert_at = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if stripped and not stripped.startswith("--"):
            insert_at = i
            break
    lines.insert(insert_at, OPM_HEADER)
    text = "\n".join(lines)

    print(f"  Clean deck: {len(text):,} characters")

    with open(dst, "w", errors="replace") as fh:
        fh.write(text)

    print(f"  Written: {dst}  ({os.path.getsize(dst):,} bytes)")
    print()
    sys.exit(0)


if __name__ == "__main__":
    main()
